# Generated by Django 4.1.2 on 2023-02-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
    ]
